/*
 * Ambulance Api
 *
 * Ambulance management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xkovhet@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

 package ambulance_wl

import (
   "net/http"

   "github.com/gin-gonic/gin"
)

type EmloyeeListAPI interface {

   // internal registration of api routes
   addRoutes(routerGroup *gin.RouterGroup)

    // DeleteEmployeeEntry - Deletes specific entry
   DeleteEmployeeEntry(ctx *gin.Context)

    // GetEmployeeEntry - Provides details about the employee
   GetEmployeeEntry(ctx *gin.Context)

    // GetEmployeeList - Provides details the ambulance employee list
   GetEmployeeList(ctx *gin.Context)

    // UpdateEmployeeEntry - Updates specific entry
   UpdateEmployeeEntry(ctx *gin.Context)

 }

// partial implementation of EmloyeeListAPI - all functions must be implemented in add on files
type implEmloyeeListAPI struct {

}

func newEmloyeeListAPI() EmloyeeListAPI {
  return &implEmloyeeListAPI{}
}

func (this *implEmloyeeListAPI) addRoutes(routerGroup *gin.RouterGroup) {
  routerGroup.Handle( http.MethodDelete, "/ambulances/:ambulanceId/employees/:employeeId", this.DeleteEmployeeEntry)
  routerGroup.Handle( http.MethodGet, "/ambulances/:ambulanceId/employees/:employeeId", this.GetEmployeeEntry)
  routerGroup.Handle( http.MethodGet, "/ambulances/:ambulanceId/employees", this.GetEmployeeList)
  routerGroup.Handle( http.MethodPut, "/ambulances/:ambulanceId/employees/:employeeId", this.UpdateEmployeeEntry)
}

// Copy following section to separate file, uncomment, and implement accordingly
// // DeleteEmployeeEntry - Deletes specific entry
// func (this *implEmloyeeListAPI) DeleteEmployeeEntry(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // GetEmployeeEntry - Provides details about the employee
// func (this *implEmloyeeListAPI) GetEmployeeEntry(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // GetEmployeeList - Provides details the ambulance employee list
// func (this *implEmloyeeListAPI) GetEmployeeList(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // UpdateEmployeeEntry - Updates specific entry
// func (this *implEmloyeeListAPI) UpdateEmployeeEntry(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//

