/*
 * Ambulance Api
 *
 * Ambulance management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xkovhet@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance_wl

type AmbulanceResponse struct {

	// Unique id of the ambulance
	Id string `json:"id"`

	// Name of ambulance
	Name string `json:"name"`

	// Location of ambulance
	Location string `json:"location"`

	// Contact for ambulance
	Contact string `json:"contact"`

	// Number of nurses
	NurseCount int32 `json:"nurseCount"`

	// Number of doctors
	DoctorCount int32 `json:"doctorCount"`

	// Total wage of nurses
	NurseTotalWage int32 `json:"nurseTotalWage"`

	// Total wage of doctors
	DoctorTotalWage int32 `json:"doctorTotalWage"`
}

func MapAmbulanceToResponse(ambulance Ambulance) AmbulanceResponse {
	var nurseCount, doctorCount int32
	for _, employee := range ambulance.Employees {
		switch employee.Position {
		case "Nurse":
			nurseCount++
		case "Doctor":
			doctorCount++
		}
	}

	return AmbulanceResponse{
		Id:          ambulance.Id,
		Name:        ambulance.Name,
		Location:    ambulance.Location,
		Contact:     ambulance.Contact,
		NurseCount:  nurseCount,
		DoctorCount: doctorCount,
	}
}